title: Forms
modelClass: AdrisonLuz\NanoCms\Models\Form
list: $/adrisonluz/nanocms/models/form/columns.yaml
recordUrl: 'adrisonluz/nanocms/forms/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
