plugin:
    name: 'adrisonluz.nanocms::lang.plugin.name'
    description: 'adrisonluz.nanocms::lang.plugin.description'
    author: 'Adrison Luz'
    icon: oc-icon-cube
    homepage: ''
navigation:
    agenda:
        label: 'Nano CMS'
        url: adrisonluz/nanocms/agendas
        icon: icon-cube
        permissions:
            - nanocms_agenda
        order: ''
        sideMenu:
            agenda:
                label: Agenda
                url: adrisonluz/nanocms/agendas
                icon: icon-calendar
                permissions:
                    - nanocms_agenda
permissions:
    nanocms_agenda:
        tab: 'Nano CMS'
        label: 'Nano CMS | Agenda'
    nanocms_banners:
        tab: 'Nano CMS'
        label: 'Nano CMS | Banners'
    nanocms_blocos:
        tab: 'Nano CMS'
        label: 'Nano CMS | Blocos'
    nanocms_categorias:
        tab: 'Nano CMS'
        label: 'Nano CMS | Categorias'
    nanocms_fields:
        tab: 'Nano CMS'
        label: 'Nano CMS | Fields'
    nanocms_forms:
        tab: 'Nano CMS'
        label: 'Nano CMS | Forms'
    nanocms_galerias:
        tab: 'Nano CMS'
        label: 'Nano CMS | Galerias'
    nanocms_menus:
        tab: 'Nano CMS'
        label: 'Nano CMS | Menus'
    nanocms_paginas:
        tab: 'Nano CMS'
        label: 'Nano CMS | Páginas'
    nanocms_posts:
        tab: 'Nano CMS'
        label: 'Nano CMS | Posts'
    nanocms_seo:
        tab: 'Nano CMS'
        label: 'Nano CMS | SEO'
    nanocms_dashboard:
        tab: 'Nano CMS'
        label: 'Nano CMS | Dashboard'
