plugin:
    name: 'adrisonluz.nanocms::lang.plugin.name'
    description: 'adrisonluz.nanocms::lang.plugin.description'
    author: 'Adrison Luz'
    icon: oc-icon-cube
    homepage: ''
navigation:
    agenda:
        label: 'Nano CMS'
        url: adrisonluz/nanocms/agendas
        icon: icon-cube
        permissions:
            - nanocms_agenda
        order: ''
        sideMenu:
            agenda:
                label: Agenda
                url: adrisonluz/nanocms/agendas
                icon: icon-calendar
                permissions:
                    - nanocms_agenda
permissions:
    nanocms_agenda:
        tab: 'Nano CMS | Agenda'
        label: 'Nano CMS | Agenda'
