plugin:
    name: 'adrisonluz.nanocms::lang.plugin.name'
    description: 'adrisonluz.nanocms::lang.plugin.description'
    author: 'Adrison Luz'
    icon: oc-icon-cube
    homepage: ''
navigation:
    geral:
        label: 'Nano CMS'
        url: adrisonluz/nanocms/banners
        icon: icon-cube
        permissions:
            - nanocms_geral
        order: '10'
        sideMenu:
            banners:
                label: Banners
                url: adrisonluz/nanocms/banners
                icon: icon-image
                permissions:
                    - nanocms_banners
            posts:
                label: Posts
                url: adrisonluz/nanocms/posts
                icon: icon-pencil-square-o
                permissions:
                    - nanocms_posts
            categorias:
                label: Categorias
                url: adrisonluz/nanocms/categorias
                icon: icon-sitemap
                permissions:
                    - nanocms_categorias
            paginas:
                label: P치ginas
                url: adrisonluz/nanocms/paginas
                icon: icon-file-text-o
                permissions:
                    - nanocms_paginas
            galerias:
                label: Galerias
                url: adrisonluz/nanocms/galerias
                icon: icon-film
                permissions:
                    - nanocms_galerias
            forms:
                label: Formul치rios
                url: adrisonluz/nanocms/forms
                icon: icon-list-alt
                permissions:
                    - nanocms_forms
            fields:
                label: Fields
                url: adrisonluz/nanocms/fields
                icon: icon-list
                permissions:
                    - nanocms_fields
                    - nanocms_forms
            mascaras:
                label: M치scaras
                url: adrisonluz/nanocms/mascara
                icon: icon-terminal
                permissions:
                    - nanocms_forms
                    - nanocms_fields
            menus:
                label: Menus
                url: adrisonluz/nanocms/menus
                icon: icon-exchange
                permissions:
                    - nanocms_menus
            menu-itens:
                label: 'Menu Itens'
                url: adrisonluz/nanocms/menuitens
                icon: icon-link
                permissions:
                    - nanocms_menus
            agenda:
                label: Agenda
                url: adrisonluz/nanocms/agendas
                icon: icon-calendar
                permissions:
                    - nanocms_agenda
permissions:
    nanocms_geral:
        tab: 'Nano CMS'
        label: 'Nano CMS | Geral'
        order: 1
    nanocms_dashboard:
        tab: 'Nano CMS'
        label: 'Nano CMS | Dashboard'
        order: 1
    nanocms_agenda:
        tab: 'Nano CMS'
        label: 'Nano CMS | Agenda'
        order: 10
    nanocms_banners:
        tab: 'Nano CMS'
        label: 'Nano CMS | Banners'
        order: 2
    nanocms_blocos:
        tab: 'Nano CMS'
        label: 'Nano CMS | Blocos'
        order: 12
    nanocms_categorias:
        tab: 'Nano CMS'
        label: 'Nano CMS | Categorias'
        order: 4
    nanocms_fields:
        tab: 'Nano CMS'
        label: 'Nano CMS | Fields'
        order: 8
    nanocms_forms:
        tab: 'Nano CMS'
        label: 'Nano CMS | Forms'
        order: 7
    nanocms_galerias:
        tab: 'Nano CMS'
        label: 'Nano CMS | Galerias'
        order: 6
    nanocms_menus:
        tab: 'Nano CMS'
        label: 'Nano CMS | Menus'
        order: 9
    nanocms_paginas:
        tab: 'Nano CMS'
        label: 'Nano CMS | P치ginas'
        order: 5
    nanocms_posts:
        tab: 'Nano CMS'
        label: 'Nano CMS | Posts'
        order: 3
    nanocms_seo:
        tab: 'Nano CMS'
        label: 'Nano CMS | SEO'
        order: 11
