title: Posts
modelClass: AdrisonLuz\NanoCms\Models\Post
list: $/adrisonluz/nanocms/models/post/columns.yaml
recordUrl: 'adrisonluz/nanocms/posts/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
