title: Categorias
modelClass: AdrisonLuz\NanoCms\Models\Categoria
list: $/adrisonluz/nanocms/models/categoria/columns.yaml
recordUrl: 'adrisonluz/nanocms/categorias/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
