title: Agendas
modelClass: AdrisonLuz\NanoCms\Models\Agenda
list: $/adrisonluz/nanocms/models/agenda/columns.yaml
recordUrl: 'adrisonluz/nanocms/agendas/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
