title: Menus
modelClass: AdrisonLuz\NanoCms\Models\Menu
list: $/adrisonluz/nanocms/models/menu/columns.yaml
recordUrl: 'adrisonluz/nanocms/menus/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
