title: Banners
modelClass: AdrisonLuz\NanoCms\Models\Banner
list: $/adrisonluz/nanocms/models/banner/columns.yaml
recordUrl: 'adrisonluz/nanocms/banners/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
